<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
                                  'key' => 'group_607b352316adc',
                                  'title' => 'contact us',
                                  'fields' => array(
                                      array(
                                          'key' => 'field_607b358207ec2',
                                          'label' => 'google map',
                                          'name' => 'google_map',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 1,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_607b359d07ec3',
                                          'label' => 'contact with manager',
                                          'name' => 'contact_with_manager',
                                          'type' => 'wysiwyg',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'tabs' => 'all',
                                          'toolbar' => 'full',
                                          'media_upload' => 0,
                                          'delay' => 0,
                                      ),
                                      array(
                                          'key' => 'field_607b35bc07ec4',
                                          'label' => 'contact with customer section',
                                          'name' => 'contact_with_customer_section',
                                          'type' => 'wysiwyg',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'tabs' => 'all',
                                          'toolbar' => 'full',
                                          'media_upload' => 1,
                                          'delay' => 0,
                                      ),
                                  ),
                                  'location' => array(
                                      array(
                                          array(
                                              'param' => 'page_template',
                                              'operator' => '==',
                                              'value' => 'templates/contact.php',
                                          ),
                                      ),
                                  ),
                                  'menu_order' => 0,
                                  'position' => 'normal',
                                  'style' => 'default',
                                  'label_placement' => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen' => array(
                                      0 => 'the_content',
                                      1 => 'excerpt',
                                      2 => 'discussion',
                                      3 => 'comments',
                                      4 => 'revisions',
                                      5 => 'author',
                                      6 => 'format',
                                      7 => 'featured_image',
                                      8 => 'categories',
                                      9 => 'tags',
                                      10 => 'send-trackbacks',
                                  ),
                                  'active' => true,
                                  'description' => '',
                              ));

endif;

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
                                  'key' => 'group_60ab6c1ea4c9f',
                                  'title' => 'home page',
                                  'fields' => array(
                                      array(
                                          'key' => 'field_60ab6e92dfb47',
                                          'label' => 'بخش بالا',
                                          'name' => 'top_section',
                                          'type' => 'group',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'layout' => 'row',
                                          'sub_fields' => array(
                                              array(
                                                  'key' => 'field_60ab6ccf43495',
                                                  'label' => 'تصویر بالا',
                                                  'name' => 'top-picture',
                                                  'type' => 'select',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'choices' => array(
                                                      'image' => 'image',
                                                      'slider shortcode' => 'slider shortcode',
                                                  ),
                                                  'default_value' => 'image',
                                                  'allow_null' => 0,
                                                  'multiple' => 0,
                                                  'ui' => 1,
                                                  'ajax' => 0,
                                                  'return_format' => 'value',
                                                  'placeholder' => '',
                                              ),
                                              array(
                                                  'key' => 'field_60ab6d2e43496',
                                                  'label' => 'انتخاب تصویر',
                                                  'name' => 'select_picture',
                                                  'type' => 'image',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => array(
                                                      array(
                                                          array(
                                                              'field' => 'field_60ab6ccf43495',
                                                              'operator' => '==',
                                                              'value' => 'image',
                                                          ),
                                                      ),
                                                  ),
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'return_format' => 'array',
                                                  'preview_size' => 'full',
                                                  'library' => 'all',
                                                  'min_width' => '',
                                                  'min_height' => '',
                                                  'min_size' => '',
                                                  'max_width' => '',
                                                  'max_height' => '',
                                                  'max_size' => '',
                                                  'mime_types' => '',
                                              ),
                                              array(
                                                  'key' => 'field_60ab6d7443497',
                                                  'label' => 'شورت کد اسلایدر',
                                                  'name' => 'slider_shortcode',
                                                  'type' => 'text',
                                                  'instructions' => 'لطفا بعد از نصب و فعال سازی و ساخت یک اسلایدر در افزونه های اسلایدر ، شورت کد آن را در این بخش وارد نمایید.',
                                                  'required' => 0,
                                                  'conditional_logic' => array(
                                                      array(
                                                          array(
                                                              'field' => 'field_60ab6ccf43495',
                                                              'operator' => '==',
                                                              'value' => 'slider shortcode',
                                                          ),
                                                      ),
                                                  ),
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'default_value' => '',
                                                  'placeholder' => '',
                                                  'prepend' => '',
                                                  'append' => '',
                                                  'maxlength' => '',
                                              ),
                                          ),
                                      ),
                                      array(
                                          'key' => 'field_60ab6eefdfb48',
                                          'label' => 'دسته بندی های برتر',
                                          'name' => 'top_categories',
                                          'type' => 'group',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'layout' => 'row',
                                          'sub_fields' => array(
                                              array(
                                                  'key' => 'field_60ab703e4b1d4',
                                                  'label' => 'آیتم 1',
                                                  'name' => 'first_item_1',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab703e4b1d5',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => '',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => '',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab703e4b1d6',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab703e4b1d7',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70404b1d8',
                                                  'label' => 'آیتم 2',
                                                  'name' => 'first_item_2',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70404b1d9',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => '',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => '',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70404b1da',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70404b1db',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70424b1dc',
                                                  'label' => 'آیتم ۳',
                                                  'name' => 'first_item_3',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70424b1dd',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => '',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => '',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70424b1de',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70424b1df',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70434b1e0',
                                                  'label' => 'آیتم ۴',
                                                  'name' => 'first_item_4',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70434b1e1',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => '',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => '',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70434b1e2',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70434b1e3',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70454b1e4',
                                                  'label' => 'آیتم ۵',
                                                  'name' => 'first_item_5',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70454b1e5',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => '',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => '',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70454b1e6',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70454b1e7',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70474b1e8',
                                                  'label' => 'آیتم ۶',
                                                  'name' => 'first_item_6',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70474b1e9',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => 'url',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => 'all',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70474b1ea',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70474b1eb',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                          ),
                                      ),
                                      array(
                                          'key' => 'field_60ab70d1f2950',
                                          'label' => 'مزایای ما',
                                          'name' => 'my_website_offer',
                                          'type' => 'group',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'layout' => 'row',
                                          'sub_fields' => array(
                                              array(
                                                  'key' => 'field_60ab70d1f2951',
                                                  'label' => 'آیتم 1',
                                                  'name' => 'first_item_1',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70d1f2952',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => 'array',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => 'all',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f2953',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab710ff2969',
                                                          'label' => 'متن پایین',
                                                          'name' => 'btn_text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f2954',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70d1f2955',
                                                  'label' => 'آیتم 2',
                                                  'name' => 'first_item_2',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70d1f2956',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => 'array',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => 'all',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f2957',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab7123f296a',
                                                          'label' => 'متن پایین',
                                                          'name' => 'btn_text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f2958',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key' => 'field_60ab70d1f2959',
                                                  'label' => 'آیتم ۳',
                                                  'name' => 'first_item_3',
                                                  'type' => 'group',
                                                  'instructions' => '',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'layout' => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key' => 'field_60ab70d1f295a',
                                                          'label' => 'تصویر',
                                                          'name' => 'image',
                                                          'type' => 'image',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'return_format' => 'array',
                                                          'preview_size' => 'thumbnail',
                                                          'library' => 'all',
                                                          'min_width' => '',
                                                          'min_height' => '',
                                                          'min_size' => '',
                                                          'max_width' => '',
                                                          'max_height' => '',
                                                          'max_size' => '',
                                                          'mime_types' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f295b',
                                                          'label' => 'متن',
                                                          'name' => 'text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab7136f296b',
                                                          'label' => 'متن پایین',
                                                          'name' => 'btn_text',
                                                          'type' => 'text',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'default_value' => '',
                                                          'placeholder' => '',
                                                          'prepend' => '',
                                                          'append' => '',
                                                          'maxlength' => '',
                                                      ),
                                                      array(
                                                          'key' => 'field_60ab70d1f295c',
                                                          'label' => 'لینک',
                                                          'name' => 'link',
                                                          'type' => 'page_link',
                                                          'instructions' => '',
                                                          'required' => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper' => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id' => '',
                                                          ),
                                                          'post_type' => array(
                                                              0 => 'post',
                                                              1 => 'product',
                                                          ),
                                                          'taxonomy' => '',
                                                          'allow_null' => 0,
                                                          'allow_archives' => 1,
                                                          'multiple' => 0,
                                                      ),
                                                  ),
                                              ),
                                          ),
                                      ),
                                  ),
                                  'location' => array(
                                      array(
                                          array(
                                              'param' => 'post_template',
                                              'operator' => '==',
                                              'value' => 'templates/front-1.php',
                                          ),
                                      ),
                                  ),
                                  'menu_order' => 0,
                                  'position' => 'normal',
                                  'style' => 'default',
                                  'label_placement' => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen' => array(
                                      0 => 'the_content',
                                      1 => 'excerpt',
                                      2 => 'discussion',
                                      3 => 'comments',
                                      4 => 'revisions',
                                      5 => 'author',
                                      6 => 'format',
                                      7 => 'featured_image',
                                      8 => 'categories',
                                      9 => 'tags',
                                      10 => 'send-trackbacks',
                                  ),
                                  'active' => true,
                                  'description' => '',
                              ));

    acf_add_local_field_group(array(
                                  'key' => 'group_608fa629d7829',
                                  'title' => 'product',
                                  'fields' => array(
                                      array(
                                          'key' => 'field_608fa6423007a',
                                          'label' => 'مناسب برای',
                                          'name' => 'created_for',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '20',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                      ),
                                      array(
                                          'key' => 'field_608fb7513083c',
                                          'label' => 'ویژگی های محصول',
                                          'name' => 'product_specifications',
                                          'type' => 'checkbox',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'choices' => array(
                                              'جنس: نخ' => 'جنس: نخ',
                                              'مناسب فصل: تابستان' => 'مناسب فصل: تابستان',
                                              'تراکم ۵۰' => 'تراکم ۵۰',
                                              '' => '',
                                          ),
                                          'allow_custom' => 1,
                                          'save_custom' => 1,
                                          'default_value' => array(
                                          ),
                                          'layout' => 'horizontal',
                                          'toggle' => 0,
                                          'return_format' => 'value',
                                      ),
                                      array(
                                          'key' => 'field_608fd2d3923b3',
                                          'label' => 'ارسال از',
                                          'name' => 'send_from',
                                          'type' => 'select',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '20',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'choices' => array(
                                              'فروشنده' => 'فروشنده',
                                              'انبار مرکزی' => 'انبار مرکزی',
                                          ),
                                          'default_value' => false,
                                          'allow_null' => 0,
                                          'multiple' => 0,
                                          'ui' => 1,
                                          'ajax' => 0,
                                          'return_format' => 'value',
                                          'placeholder' => '',
                                      ),
                                      array(
                                          'key' => 'field_608fe2b476745',
                                          'label' => 'نقد و بررسی',
                                          'name' => 'review',
                                          'type' => 'wysiwyg',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'default_value' => '',
                                          'tabs' => 'all',
                                          'toolbar' => 'full',
                                          'media_upload' => 1,
                                          'delay' => 0,
                                      ),
                                      array(
                                          'key' => 'field_608febc85b1e6',
                                          'label' => 'مزیت',
                                          'name' => 'advantage',
                                          'type' => 'checkbox',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'choices' => array(
                                          ),
                                          'allow_custom' => 1,
                                          'save_custom' => 0,
                                          'default_value' => array(
                                          ),
                                          'layout' => 'horizontal',
                                          'toggle' => 0,
                                          'return_format' => 'value',
                                      ),
                                      array(
                                          'key' => 'field_608fec1b5b1e7',
                                          'label' => 'معایت',
                                          'name' => 'disadvantages',
                                          'type' => 'checkbox',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'choices' => array(
                                          ),
                                          'allow_custom' => 1,
                                          'save_custom' => 0,
                                          'default_value' => array(
                                          ),
                                          'layout' => 'horizontal',
                                          'toggle' => 0,
                                          'return_format' => 'value',
                                      ),
                                      array(
                                          'key' => 'field_608fee6bf663c',
                                          'label' => 'گروه درصد نقد و بررسی',
                                          'name' => 'review_group',
                                          'type' => 'group',
                                          'instructions' => '',
                                          'required' => 0,
                                          'conditional_logic' => 0,
                                          'wrapper' => array(
                                              'width' => '40',
                                              'class' => '',
                                              'id' => '',
                                          ),
                                          'layout' => 'block',
                                          'sub_fields' => array(
                                              array(
                                                  'key' => 'field_608feea3f663d',
                                                  'label' => 'جنس بافت',
                                                  'name' => 'materials_woven',
                                                  'type' => 'number',
                                                  'instructions' => 'درصد خوب بودن جنس بافت',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'default_value' => '',
                                                  'placeholder' => '',
                                                  'prepend' => '',
                                                  'append' => '',
                                                  'min' => 0,
                                                  'max' => 100,
                                                  'step' => '',
                                              ),
                                              array(
                                                  'key' => 'field_608feee2f663e',
                                                  'label' => 'کیفیت دوخت',
                                                  'name' => 'sewing_quality',
                                                  'type' => 'number',
                                                  'instructions' => 'درصد خوب بودن جنس بافت',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'default_value' => '',
                                                  'placeholder' => '',
                                                  'prepend' => '',
                                                  'append' => '',
                                                  'min' => 0,
                                                  'max' => 100,
                                                  'step' => '',
                                              ),
                                              array(
                                                  'key' => 'field_608fef20f6640',
                                                  'label' => 'رضایت مشتریان',
                                                  'name' => 'customer_satisfaction',
                                                  'type' => 'number',
                                                  'instructions' => 'درصد خوب بودن جنس بافت',
                                                  'required' => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper' => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id' => '',
                                                  ),
                                                  'default_value' => '',
                                                  'placeholder' => '',
                                                  'prepend' => '',
                                                  'append' => '',
                                                  'min' => 0,
                                                  'max' => 100,
                                                  'step' => '',
                                              ),
                                          ),
                                      ),
                                  ),
                                  'location' => array(
                                      array(
                                          array(
                                              'param' => 'post_type',
                                              'operator' => '==',
                                              'value' => 'product',
                                          ),
                                      ),
                                  ),
                                  'menu_order' => 0,
                                  'position' => 'normal',
                                  'style' => 'default',
                                  'label_placement' => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen' => '',
                                  'active' => true,
                                  'description' => '',
                              ));

endif;